package com.cudirect.membershipeligibility;
import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantsEligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.math.BigInteger id;
	@org.kie.api.definition.type.Label(value = "ApplicantsEligibleLenders")
	private java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders;

	public ApplicantsEligibility() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> getApplicantsEligibleLenders() {
		return this.applicantsEligibleLenders;
	}

	public void setApplicantsEligibleLenders(
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders) {
		this.applicantsEligibleLenders = applicantsEligibleLenders;
	}

	public ApplicantsEligibility(
			java.math.BigInteger id,
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders) {
		this.id = id;
		this.applicantsEligibleLenders = applicantsEligibleLenders;
	}
    
    public void addCuEligibility(ApplicantCuEligibility applicantsEligibleLender)
    {
    	if(this.applicantsEligibleLenders == null)
    	{
    		this.applicantsEligibleLenders = new ArrayList<ApplicantCuEligibility>();
    	}
    	this.applicantsEligibleLenders.add(applicantsEligibleLender);
    }
    
    @Override
	public String toString() {
		return "ApplicantsEligibileLender [" + (id != null ? "id=" + id + ", " : "")
				+ (applicantsEligibleLenders != null ? "applicantsEligibleLenders=" + applicantsEligibleLenders : "")
				+ "]";
	}
}