package com.cudirect.membershipeligibility;
import com.cudirect.membershipeligibility.*;
import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Applicant")
	private com.cudirect.membershipeligibility.Applicant applicant;
	@org.kie.api.definition.type.Label(value = "applicants Eligible Lenders List")
	private java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders;
	private com.cudirect.membershipeligibility.ApplicantCuEligibility applicantCueligibility;

	public Application() {
	}

	public com.cudirect.membershipeligibility.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(
			com.cudirect.membershipeligibility.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> getApplicantsEligibleLenders() {
		return this.applicantsEligibleLenders;
	}

	public void setApplicantsEligibleLenders(
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders) {
		this.applicantsEligibleLenders = applicantsEligibleLenders;
	}

	public Application(
			com.cudirect.membershipeligibility.Applicant applicant,
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders) {
		this.applicant = applicant;
		this.applicantsEligibleLenders = applicantsEligibleLenders;
	}

   public void AddApplicantEligibleLender(String eligibilityCode, String lenderCode)
   {
       
           if(this.applicantsEligibleLenders == null)
           {
                this.applicantsEligibleLenders = new ArrayList<com.cudirect.membershipeligibility.ApplicantCuEligibility>();               
           }
          applicantCueligibility = new ApplicantCuEligibility();
           applicantCueligibility.setEligibilityCode(eligibilityCode);
           applicantCueligibility.setLenderCode(lenderCode);
           this.applicantsEligibleLenders.add(applicantCueligibility);
       
   }
}