package com.cudirect.membershipeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantCuEligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ApplicantId")
	private java.math.BigInteger applicantId;
	@org.kie.api.definition.type.Label("LenderCode")
	private java.lang.String lenderCode;
	@org.kie.api.definition.type.Label("Eligibility Code")
	private java.lang.String eligibilityCode;

	public ApplicantCuEligibility() {
	}

	public java.math.BigInteger getApplicantId() {
		return this.applicantId;
	}

	public void setApplicantId(java.math.BigInteger applicantId) {
		this.applicantId = applicantId;
	}

	public java.lang.String getLenderCode() {
		return this.lenderCode;
	}

	public void setLenderCode(java.lang.String lenderCode) {
		this.lenderCode = lenderCode;
	}

	public java.lang.String getEligibilityCode() {
		return this.eligibilityCode;
	}

	public void setEligibilityCode(java.lang.String eligibilityCode) {
		this.eligibilityCode = eligibilityCode;
	}

	public ApplicantCuEligibility(java.math.BigInteger applicantId,
			java.lang.String lenderCode, java.lang.String eligibilityCode) {
		this.applicantId = applicantId;
		this.lenderCode = lenderCode;
		this.eligibilityCode = eligibilityCode;
	}

}