package com.cudirect.membershipeligibility;
import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Applicant Id")
	private java.math.BigInteger applicantId;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Address1")
	private java.lang.String address1;
	@org.kie.api.definition.type.Label("Address2")
	private java.lang.String address2;
	@org.kie.api.definition.type.Label("City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label("County")
	private java.lang.String county;
	@org.kie.api.definition.type.Label("Zipcode")
	private java.lang.String zipcode;
	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("Date Of Birth")
	private java.util.Date dateOfBirth;

	@org.kie.api.definition.type.Label("Employer Organization Name")
	private java.lang.String employerOrganizationName;

	@org.kie.api.definition.type.Label("Employer Location City")
	private java.lang.String employerLocationCity;

	@org.kie.api.definition.type.Label("ApplicantsEligibleLenders")
	private java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders;

	@org.kie.api.definition.type.Label("EligibleLenderCodes")
	private java.util.List<java.lang.String> eligibleLenderCodes;

	@org.kie.api.definition.type.Label("LenderCode")
	private java.lang.String lenderCode;

	@org.kie.api.definition.type.Label(value = "EligibilityCode")
	private java.lang.String eligibilityCode;

	public Applicant() {
	}

	public java.math.BigInteger getApplicantId() {
		return this.applicantId;
	}

	public void setApplicantId(java.math.BigInteger applicantId) {
		this.applicantId = applicantId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress1() {
		return this.address1;
	}

	public void setAddress1(java.lang.String address1) {
		this.address1 = address1;
	}

	public java.lang.String getAddress2() {
		return this.address2;
	}

	public void setAddress2(java.lang.String address2) {
		this.address2 = address2;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCounty() {
		return this.county;
	}

	public void setCounty(java.lang.String county) {
		this.county = county;
	}

	public java.lang.String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(java.lang.String zipcode) {
		this.zipcode = zipcode;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.util.Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.util.Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getEmployerOrganizationName() {
		return this.employerOrganizationName;
	}

	public void setEmployerOrganizationName(
			java.lang.String employerOrganizationName) {
		this.employerOrganizationName = employerOrganizationName;
	}

	public java.lang.String getEmployerLocationCity() {
		return this.employerLocationCity;
	}

	public void setEmployerLocationCity(java.lang.String employerLocationCity) {
		this.employerLocationCity = employerLocationCity;
	}
	public java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> getApplicantsEligibleLenders() {
		return this.applicantsEligibleLenders;
	}

	public void setApplicantsEligibleLenders(
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders) {
		this.applicantsEligibleLenders = applicantsEligibleLenders;
	}
	public void addCuEligibility(ApplicantCuEligibility applicantsEligibleLender) {
		if (this.applicantsEligibleLenders == null) {
			this.applicantsEligibleLenders = new ArrayList<ApplicantCuEligibility>();
		}
		this.applicantsEligibleLenders.add(applicantsEligibleLender);
	}

	public void addEligibleLenderCode(String lenderCode) {
		if (this.eligibleLenderCodes == null) {
			this.eligibleLenderCodes = new ArrayList<java.lang.String>();
		}
		this.eligibleLenderCodes.add(lenderCode);
	}

	public java.util.List<java.lang.String> getEligibleLenderCodes() {
		return this.eligibleLenderCodes;
	}

	public void setEligibleLenderCodes(
			java.util.List<java.lang.String> eligibleLenderCodes) {
		this.eligibleLenderCodes = eligibleLenderCodes;
	}

	public java.lang.String getLenderCode() {
		return this.lenderCode;
	}

	public void setLenderCode(java.lang.String lenderCode) {
		this.lenderCode = lenderCode;
	}

	public java.lang.String getEligibilityCode() {
		return this.eligibilityCode;
	}

	public void setEligibilityCode(java.lang.String eligibilityCode) {
		this.eligibilityCode = eligibilityCode;
	}

	public Applicant(
			java.math.BigInteger applicantId,
			java.lang.String name,
			java.lang.String address1,
			java.lang.String address2,
			java.lang.String city,
			java.lang.String county,
			java.lang.String zipcode,
			java.lang.String state,
			java.util.Date dateOfBirth,
			java.lang.String employerOrganizationName,
			java.lang.String employerLocationCity,
			java.util.List<com.cudirect.membershipeligibility.ApplicantCuEligibility> applicantsEligibleLenders,
			java.util.List<java.lang.String> eligibleLenderCodes,
			java.lang.String lenderCode, java.lang.String eligibilityCode) {
		this.applicantId = applicantId;
		this.name = name;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.county = county;
		this.zipcode = zipcode;
		this.state = state;
		this.dateOfBirth = dateOfBirth;
		this.employerOrganizationName = employerOrganizationName;
		this.employerLocationCity = employerLocationCity;
		this.applicantsEligibleLenders = applicantsEligibleLenders;
		this.eligibleLenderCodes = eligibleLenderCodes;
		this.lenderCode = lenderCode;
		this.eligibilityCode = eligibilityCode;
	}

}