package com.cudirect.membershipeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditUnion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public CreditUnion() {
	}

}