package com.cudirect.membershipeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CuLocationEligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.math.BigInteger id;
	@org.kie.api.definition.type.Label(value = "LenderName")
	private java.lang.String lenderName;
	@org.kie.api.definition.type.Label(value = "LenderCode")
	private java.lang.String lenderCode;
	@org.kie.api.definition.type.Label(value = "Zip Code")
	private java.lang.String zipcode;
	@org.kie.api.definition.type.Label(value = "City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label(value = "County")
	private java.lang.String county;
	@org.kie.api.definition.type.Label(value = "State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "Eligibility Code")
	private java.lang.String eligibilityCode;

	public CuLocationEligibility() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public java.lang.String getLenderName() {
		return this.lenderName;
	}

	public void setLenderName(java.lang.String lenderName) {
		this.lenderName = lenderName;
	}

	public java.lang.String getLenderCode() {
		return this.lenderCode;
	}

	public void setLenderCode(java.lang.String lenderCode) {
		this.lenderCode = lenderCode;
	}

	public java.lang.String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(java.lang.String zipcode) {
		this.zipcode = zipcode;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCounty() {
		return this.county;
	}

	public void setCounty(java.lang.String county) {
		this.county = county;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getEligibilityCode() {
		return this.eligibilityCode;
	}

	public void setEligibilityCode(java.lang.String eligibilityCode) {
		this.eligibilityCode = eligibilityCode;
	}

	public CuLocationEligibility(java.math.BigInteger id,
			java.lang.String lenderName, java.lang.String lenderCode,
			java.lang.String zipcode, java.lang.String city,
			java.lang.String county, java.lang.String state,
			java.lang.String eligibilityCode) {
		this.id = id;
		this.lenderName = lenderName;
		this.lenderCode = lenderCode;
		this.zipcode = zipcode;
		this.city = city;
		this.county = county;
		this.state = state;
		this.eligibilityCode = eligibilityCode;
	}

}