package com.cudirect.membershipeligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CuOrganizationEligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.math.BigInteger id;
	@org.kie.api.definition.type.Label(value = "Lender Name")
	private java.lang.String lenderName;
	@org.kie.api.definition.type.Label(value = "Lender Code")
	private java.lang.String lenderCode;
	@org.kie.api.definition.type.Label(value = "OrgName")
	private java.lang.String orgName;
	@org.kie.api.definition.type.Label(value = "Address1")
	private java.lang.String address1;
	@org.kie.api.definition.type.Label(value = "Address2")
	private java.lang.String address2;
	@org.kie.api.definition.type.Label(value = "City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label(value = "County")
	private java.lang.String county;
	@org.kie.api.definition.type.Label(value = "Zip Code")
	private java.lang.String zipcode;
	@org.kie.api.definition.type.Label(value = "State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "Eligibility Code")
	private java.lang.String eligibilityCode;

	public CuOrganizationEligibility() {
	}

	public java.math.BigInteger getId() {
		return this.id;
	}

	public void setId(java.math.BigInteger id) {
		this.id = id;
	}

	public java.lang.String getLenderName() {
		return this.lenderName;
	}

	public void setLenderName(java.lang.String lenderName) {
		this.lenderName = lenderName;
	}

	public java.lang.String getLenderCode() {
		return this.lenderCode;
	}

	public void setLenderCode(java.lang.String lenderCode) {
		this.lenderCode = lenderCode;
	}

	public java.lang.String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(java.lang.String orgName) {
		this.orgName = orgName;
	}

	public java.lang.String getAddress1() {
		return this.address1;
	}

	public void setAddress1(java.lang.String address1) {
		this.address1 = address1;
	}

	public java.lang.String getAddress2() {
		return this.address2;
	}

	public void setAddress2(java.lang.String address2) {
		this.address2 = address2;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCounty() {
		return this.county;
	}

	public void setCounty(java.lang.String county) {
		this.county = county;
	}

	public java.lang.String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(java.lang.String zipcode) {
		this.zipcode = zipcode;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getEligibilityCode() {
		return this.eligibilityCode;
	}

	public void setEligibilityCode(java.lang.String eligibilityCode) {
		this.eligibilityCode = eligibilityCode;
	}

	public CuOrganizationEligibility(java.math.BigInteger id,
			java.lang.String lenderName, java.lang.String lenderCode,
			java.lang.String orgName, java.lang.String address1,
			java.lang.String address2, java.lang.String city,
			java.lang.String county, java.lang.String zipcode,
			java.lang.String state, java.lang.String eligibilityCode) {
		this.id = id;
		this.lenderName = lenderName;
		this.lenderCode = lenderCode;
		this.orgName = orgName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.county = county;
		this.zipcode = zipcode;
		this.state = state;
		this.eligibilityCode = eligibilityCode;
	}

}